---
title: "CAET Dimension Score T-Tests"
output: html_document
date: "2024-03-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    error = FALSE,
    message = FALSE
)

#renv::restore()

# Load Libraries
library(tidyverse)
library(openxlsx)
library(flextable)
library(fmsb)

#read in performance data
Main_Survey <- read.xlsx("FILEPATH TO DATA HERE",
                        sheet = "Main Survey",
                        check.names = TRUE)%>%
  filter(team_name == "Kenya Team")

#import functions to use for analysis
source("../functions.R")
```

```{r}
Main_Survey %>%        
    dplyr::select(starts_with("stand_"), pro_soils_group) %>%
        tidyr::pivot_longer(cols = starts_with("stand_"), names_to = "dimension") %>%
        dplyr::mutate(
            dimension = case_when(
            dimension == "stand_diversity" ~ "Diversity",
            dimension == "stand_syn" ~ "Synergies",
            dimension == "stand_rec" ~ "Recycling",
            dimension == "stand_eff" ~ "Efficiency",
            dimension == "stand_res" ~ "Resillience",
            dimension == "stand_cultfood" ~ "Culture \n&\n Food Tradition",
            dimension == "stand_cocrea" ~ "Co-creation\n&\nSharing\nof Knowledge",
            dimension == "stand_human" ~ "Human\n&\nSocial Values",
            dimension == "stand_circular" ~ "Circular\n&\nSolidarity Economy",
            dimension == "stand_respgov" ~ "Responsible\nGovernance"
            )
        )%>%
            tidyr::nest(data = c(value, pro_soils_group)) %>%
            dplyr::mutate(data = purrr::map(data, ~ {
                out <- t.test(.x$value ~ .x$pro_soils_group)
                tibble::tibble(
                    "Non-ProSoils" = out$estimate[1],
                    "ProSoils" = out$estimate[2],
                    Difference = out$estimate[1] - out$estimate[2],
                    `t-value` = out$statistic,
                    p.value = out$p.value
                )
            })) %>%
            tidyr::unnest(cols = data) %>%
            flextable::flextable() %>%
            flextable::colformat_double(j = 2:5, digits = 1) %>%
            flextable::colformat_double(j = 6, digits = 3) %>%
            flextable::theme_box() %>%
            flextable::bg(part = "all", bg = "white") %>%
            flextable::merge_v(j = 2) %>%
            flextable::autofit()
```

```{r}
Main_Survey %>%        
    dplyr::select(starts_with("stand_"), pro_soils_group, "Region" = location_level_one_name ) %>%
        tidyr::pivot_longer(cols = starts_with("stand_"), names_to = "dimension") %>%
        dplyr::mutate(
            dimension = case_when(
            dimension == "stand_diversity" ~ "Diversity",
            dimension == "stand_syn" ~ "Synergies",
            dimension == "stand_rec" ~ "Recycling",
            dimension == "stand_eff" ~ "Efficiency",
            dimension == "stand_res" ~ "Resillience",
            dimension == "stand_cultfood" ~ "Culture \n&\n Food Tradition",
            dimension == "stand_cocrea" ~ "Co-creation\n&\nSharing\nof Knowledge",
            dimension == "stand_human" ~ "Human\n&\nSocial Values",
            dimension == "stand_circular" ~ "Circular\n&\nSolidarity Economy",
            dimension == "stand_respgov" ~ "Responsible\nGovernance"
            )
        )%>%
            tidyr::nest(data = c(value, pro_soils_group)) %>%
            dplyr::mutate(data = purrr::map(data, ~ {
                out <- t.test(.x$value ~ .x$pro_soils_group)
                tibble::tibble(
                    "Non-ProSoils" = out$estimate[1],
                    "ProSoils" = out$estimate[2],
                    Difference = out$estimate[1] - out$estimate[2],
                    `t-value` = out$statistic,
                    p.value = out$p.value
                )
            })) %>%
            tidyr::unnest(cols = data) %>%
            flextable::flextable() %>%
            flextable::colformat_double(j = 3:6, digits = 1) %>%
            flextable::colformat_double(j = 7, digits = 3) %>%
            flextable::theme_box() %>%
            flextable::bg(part = "all", bg = "white") %>%
            flextable::merge_v(j = 1) %>%
            flextable::autofit()
```